### ISSUE TITLE
IllegalArgumentException: port is -1

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos-http#16]
```
Exception in thread "main" java.lang.IllegalArgumentException: port out of range:-1
	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:143)
	at java.net.InetSocketAddress.<init>(InetSocketAddress.java:224)
	at java.net.Socket.<init>(Socket.java:211)
	at org.cactoos.http.HtWire.send(HtWire.java:89)
	at org.cactoos.http.HtResponse.stream(HtResponse.java:98)
	at org.cactoos.io.TeeInput.stream(TeeInput.java:870)
	at org.cactoos.io.InputAsBytes.asBytes(InputAsBytes.java:79)
	at org.cactoos.io.BytesOf.asBytes(BytesOf.java:346)
	at org.cactoos.text.TextOf.lambda$new$0(TextOf.java:296)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.text.TextOf.asString(TextOf.java:365)
	at org.cactoos.http.HtHead.stream(HtHead.java:63)
	at org.cactoos.http.Main.main(Main.java:10)
```

Example: `new HtHead(new HtResponse("http://www.google.com")).stream();`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#16](https://github.com/yegor256/cactoos-http/issues/16) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
The job [#16](https://github.com/yegor256/cactoos-http/issues/16) assigned to @icok[/z](https://www.0crat.com/u/icok), here is [why](https://www.0crat.com/footprint/C63314D6Z/950519655); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @icok[/z](https://www.0crat.com/u/icok) resigned from [#16](https://github.com/yegor256/cactoos-http/issues/16), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @icok[/z](https://www.0crat.com/u/icok)

**Comment by 0crat** [comment]
The job [#16](https://github.com/yegor256/cactoos-http/issues/16) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1091548509); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos-http/issues/16#issuecomment-383064184))

@krzyk This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#16](https://github.com/yegor256/cactoos-http/issues/16) is [in scope](http://www.zerocracy.com/policy.html#14) for 16days
  * The role is `DEV`
  * The job is assigned to @krzyk[/z](https://www.0crat.com/u/krzyk) for [19hr](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @krzyk[/z](https://www.0crat.com/u/krzyk) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @vssekorin[/z](https://www.0crat.com/u/vssekorin): This user reported the ticket
    * @icok[/z](https://www.0crat.com/u/icok): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos-http%2316%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by krzyk** [comment]
@VsSekorin Please see #30

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for PR review

**Comment by 0crat** [comment]
> @0crat waiting for PR review ([here](https://github.com/yegor256/cactoos-http/issues/16#issuecomment-384189935))

@krzyk The impediment for [#16](https://github.com/yegor256/cactoos-http/issues/16) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@VsSekorin Changes were merged in #30, please close this issue

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#16](https://github.com/yegor256/cactoos-http/issues/16) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)
